const i18nContext = require('./helpers/i18n.cjs');
const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const code=fs.readFileSync('app/web/static/energy-ui.js','utf8');
let now=0,id=0,focus=true;const timers=new Map(),windowEvents={},docEvents={};
const document={body:{},hidden:false,hasFocus:()=>focus,querySelectorAll:()=>[],getElementById:()=>null,addEventListener:(name,fn)=>docEvents[name]=fn,dispatchEvent:event=>docEvents[event.type]?.(event)};
const window={addEventListener:(name,fn)=>windowEvents[name]=fn};
const context=vm.createContext(i18nContext({document,window,CustomEvent:class {constructor(type,options){this.type=type;this.detail=options.detail;}},MutationObserver:class{observe(){}},Date:{now:()=>now},setTimeout:(fn,ms)=>{const key=++id;timers.set(key,{fn,at:now+ms});return key},clearTimeout:key=>timers.delete(key),console}));
vm.runInContext(code,context);
const advance=async(ms)=>{const target=now+ms;while(true){const next=[...timers.entries()].filter(([,t])=>t.at<=target).sort((a,b)=>a[1].at-b[1].at)[0];if(!next)break;now=next[1].at;timers.delete(next[0]);next[1].fn();await Promise.resolve();await Promise.resolve();}now=target;};
(async()=>{
 let mail=0,tasks=0,open=false;
 window.mailaiEnergy.register('mail',()=>mail++,30000);
 window.mailaiEnergy.register('tasks',()=>tasks++,60000,()=>open);
 assert.equal(timers.size,1,'All visible refreshes share one timer');
 await advance(60000);assert.equal(mail,2);assert.equal(tasks,0,'Closed panels issue no requests');
 focus=false;windowEvents.blur();assert.equal(timers.size,0);await advance(60000);assert.equal(mail,2);
 let requested=false;window.mailaiEnergy.register('force',force=>requested=force,30000);
 window.mailaiEnergy.run('force',true);assert.equal(requested,false);
 focus=true;windowEvents.focus();await Promise.resolve();assert(requested,'A background change is delivered on focus');
 document.hidden=true;docEvents.visibilitychange();assert.equal(timers.size,0);
 document.hidden=false;docEvents.visibilitychange();await Promise.resolve();assert(timers.size<=1);
 open=true;window.mailaiEnergy.refresh();await advance(60000);assert(tasks>0);
 window.mailaiEnergy.pause();assert.equal(timers.size,0);
 window.mailaiEnergy.resume();await Promise.resolve();assert(timers.size<=1);
 let visibleSignal;document.addEventListener('mailai:foreground-changed',event=>visibleSignal=event.detail.visible);
 window.mailaiEnergy.nativeVisibility(2,false);assert.equal(visibleSignal,false);assert.equal(timers.size,0);
 windowEvents.focus();await Promise.resolve();assert.equal(timers.size,0,'Browser focus cannot override native window hiding');
 window.mailaiEnergy.nativeVisibility(3,true);assert.equal(visibleSignal,true);await Promise.resolve();assert(timers.size<=1);
 window.mailaiEnergy.nativeVisibility(2,false);await Promise.resolve();assert(window.mailaiEnergy.active(),'A delayed hide callback cannot disable a restored window');
 const workspace=fs.readFileSync('app/web/static/workspace.js','utf8');
 const slice=workspace.slice(workspace.indexOf('async function refreshTaskCenter('),workspace.indexOf('function updateFilterChips('));
 let requests=0;
 const blocked=vm.createContext(i18nContext({document:{getElementById:()=>({classList:{contains:()=>true}})},api:()=>requests++}));
 vm.runInContext(slice,blocked);await blocked.refreshTaskCenter();assert.equal(requests,0);
 console.log('PASS energy UI: one timer, closed panels, focus/visibility pause, deferred updates and resume');
})().catch(e=>{console.error(e);process.exitCode=1;});
