const {chromium} = require('playwright');
const fs = require('fs');
const assert = require('node:assert/strict');
const path = require('path');
(async () => {
 const browser = await chromium.launch({channel:'chrome', headless:true});
 try {
  const page = await browser.newPage({viewport:{width:1200,height:850}});
  await page.route('http://mailai.test/**', route => {
   if(route.request().url().includes('/preview')) return route.fulfill({json:{kind:'text',name:'通知.docx',text:'关于开展书画比赛的通知\n请各部门组织报名。\n<script>window.hacked=true</script>',message:'DOCX 正文预览，图片和原始排版请下载查看'}});
   return route.fulfill({contentType:'text/html; charset=utf-8',body:'<a class="attachment" href="/api/emails/1/attachments/0?mailai_account=test" download="通知.docx">通知.docx</a><a class="attachment-card" href="/api/emails/2/attachments/0?mailai_account=test" download="附件中心.docx">附件中心.docx</a>'});
  });
  await page.goto('http://mailai.test/');
  await page.addStyleTag({path:path.join(__dirname,'../app/web/static/attachment-preview.css')});
  await page.addScriptTag({path:path.join(__dirname,'../app/web/static/attachment-preview.js')});
  const source=fs.readFileSync(path.join(__dirname,'../app/web/static/app.js'),'utf8');
  await page.addScriptTag({content:'function activeMailAccount(){return {id:"test"}}; function mailboxResourceUrl(p){return p};'+source.slice(source.indexOf('async function downloadAttachmentInDesktop('),source.indexOf('let todoRenderLimit'))});
  await page.locator('.attachment').click();
  await page.locator('.file-preview pre').waitFor();
  assert.match(await page.locator('.file-preview pre').textContent(), /书画比赛/);
  assert.equal(await page.evaluate(()=>window.hacked), undefined);
  assert.match(await page.locator('[data-preview-download]').getAttribute('href'), /mailai_account=test/);
  await page.screenshot({path:path.join(__dirname,'../build/attachment-preview.png')});
  await page.keyboard.press('Escape');
  assert.equal(await page.locator('dialog').evaluate(el=>el.open), false);
  await page.locator('.attachment-card').click();
  await page.locator('.file-preview pre').waitFor();
  assert.equal(await page.locator('#file-preview-title').textContent(),'附件中心.docx');
  await page.setViewportSize({width:390,height:844});
  assert.ok(await page.locator('dialog').evaluate(el=>el.getBoundingClientRect().width <= innerWidth));
  await page.keyboard.press('Escape');
  await page.route('**/preview?*', route=>route.fulfill({json:{kind:'spreadsheet',sheets:[{name:'方案',rows:[['标题','数量'],['<script>window.hacked=true</script>','12']]},{name:'空表',rows:[]}],message:'Excel 预览'}}));
  await page.locator('.attachment').click();
  await page.locator('.file-sheet-scroll table').waitFor();
  assert.match(await page.locator('.file-sheet-scroll').textContent(), /12/);
  assert.equal(await page.evaluate(()=>window.hacked),undefined);
  await page.locator('.file-sheet-picker').selectOption('1');
  assert.equal(await page.locator('.file-sheet-scroll').textContent(),'此工作表为空');
  await page.keyboard.press('Escape');
  await page.setViewportSize({width:1200,height:900});
  await page.route('**/preview?*', route=>route.fulfill({json:{kind:'document',html:'<h1>项目自查通知</h1><p>请各部门核对项目进度，完成以下自查事项。</p><table><tr><th>检查事项</th><th>负责人</th></tr><tr><td>项目进度核对</td><td>项目负责人</td></tr></table><p><strong>请于本周五前反馈。</strong></p>',message:'Word 阅读视图'}}));
  await page.locator('.attachment').click();
  await page.locator('.file-reader-paper table').waitFor();
  await page.getByLabel('预览缩放').selectOption('125');
  assert.equal(await page.locator('.file-reader-paper').evaluate(el=>el.style.width),'992.5px');
  await page.getByLabel('预览缩放').selectOption('fit');
  await page.screenshot({path:path.join(__dirname,'../build/document-preview-reader.png')});
  await page.keyboard.press('Escape');
  await page.route('**/preview?*', route=>route.fulfill({json:{kind:'pdf',page:Number(new URL(route.request().url()).searchParams.get('page')||0),page_count:2,data:'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+aQ1cAAAAASUVORK5CYII=',message:'原版页面预览'}}));
  await page.locator('.attachment').click();
  await page.getByRole('button',{name:'下一页',exact:true}).click();
  await page.getByAltText('PDF 第 2 页').waitFor();
  assert.equal(await page.getByRole('button',{name:'下一页',exact:true}).isDisabled(),true);
  await page.getByRole('button',{name:'上一页',exact:true}).click();
  await page.getByAltText('PDF 第 1 页').waitFor();
  await page.keyboard.press('Escape');
  console.log('PASS document paper/table/zoom, PDF navigation and page boundaries');
  console.log('PASS Excel grid, sheet switching and escaped cells');
  console.log('PASS reading pane + attachment center preview, escaped text, account URL, Escape, narrow screen');
 } finally {await browser.close()}
})();
