const fs = require('node:fs');
const vm = require('node:vm');
const assert = require('node:assert/strict');
const source = fs.readFileSync('app/web/static/app.js', 'utf8');
const esc = s => String(s).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const ctx = vm.createContext({esc, mdToHtml:esc});
vm.runInContext(source.slice(source.indexOf('function assistantSourceItems('), source.indexOf('function setAssistantState(')), ctx);
const refs = Array.from({length:12}, (_,i)=>({id:311+i,subject:'同名邮件',from_addr:'team@example.test',date:`2026-09-${String(i+1).padStart(2,'0')}`}));
const html = ctx.assistantSourcesHtml(refs,'account-a');
assert.equal((html.match(/data-email-id=/g)||[]).length,12,'Never truncate reference history');
assert.doesNotMatch(html.split('>')[0],/\bopen\b/,'Many references should be collapsed');
assert.match(ctx.assistantSourcesHtml(refs.slice(0,3)).split('>')[0],/\bopen\b/);
assert.equal(ctx.assistantSourcesHtml([]),'');
assert.equal((ctx.assistantSourcesHtml([refs[0],refs[0],{id:'invalid'}]).match(/data-email-id=/g)||[]).length,1);
assert.match(html,/2026-09-12/,'Same subject messages retain differentiating metadata');
const body = ctx.assistantAnswerHtml('依据 [email_id:322]，另见 [email_id:311]。',[...refs],'account-a');
assert.match(body,/data-email-id="322"[^>]*>12<\/button>/);
assert.match(body,/data-email-id="311"[^>]*>1<\/button>/);
assert.match(body,/data-source-account="account-a"/);
assert.doesNotMatch(ctx.assistantAnswerHtml('[email_id:9999]',refs),/data-email-id/);
const malicious = ctx.assistantSourcesHtml([{id:1,subject:'<img src=x onerror=alert(1)>',from_addr:'" onfocus="alert(1)'}]);
assert.doesNotMatch(malicious,/<img/);
assert.match(malicious,/&lt;img/);
console.log('Reference collapse thresholds, full history, numbering, identity and escaping passed');
