const i18nContext = require('./helpers/i18n.cjs');
const fs=require('node:fs');
const vm=require('node:vm');
const assert=require('node:assert/strict');
const path=require('node:path');
const code=fs.readFileSync(path.join(__dirname,'../app/web/static/productivity.js'),'utf8');
const start=code.indexOf('  window.mailaiProductivityFilter =');
const end=code.indexOf('  window.mailaiProductivityTags =',start);
const context={window:{},specialMailbox:'',mailboxNavigationRevision:1,owner:()=> 'a',updateWorkflowRows:()=>{},labels:{reply:'待回复'},state:{navigation:1,view:'reply',conversations:false,senders:new Map()}};
vm.createContext(i18nContext(context));vm.runInContext(code.slice(start,end),context);
const rows=[{id:1,_account_id:'a',thread_id:'thread',handle_state:'reply',priority:'低',from_addr:'vip@example.test'},{id:2,_account_id:'a',thread_id:'thread',handle_state:'done'},{id:1,_account_id:'b',thread_id:'thread',handle_state:'waiting',priority:'高'}];
assert.equal(context.window.mailaiProductivityFilter(rows).length,1);
assert.equal(context.window.mailaiProductivityTitle('所有收件箱'),'所有收件箱 · 待回复');
context.state.view='all';context.state.conversations=true;
const grouped=context.window.mailaiProductivityList(rows);
assert.equal(grouped.length,2,'Same thread IDs in separate accounts cannot merge');assert.equal(grouped[0]._conversationCount,2);
context.state.view='focus';context.state.senders.set('a:vip@example.test','focus');assert.equal(context.window.mailaiProductivityFilter(rows).length,2);
rows[0].focus_override='other';assert.equal(context.window.mailaiProductivityFilter(rows).length,1);
context.specialMailbox='drafts';assert.equal(context.window.mailaiProductivityFilter(rows).length,3);assert.equal(context.window.mailaiProductivityList(rows).length,3);
const app=fs.readFileSync(path.join(__dirname,'../app/web/static/app.js'),'utf8');
assert(app.indexOf('list = window.mailaiProductivityFilter')<app.indexOf('const riskRows ='),'Facets and counts must use the filtered rows');
assert(app.includes('send_at:payload.send_at')||app.includes("send_at:payload.send_at || ''"));
console.log('PASS productivity UI: filtered counts, account-scoped conversations, VIP overrides and special mailboxes');
