// Run only against tests/workspace_preview.py, with Playwright installed.
const {chromium}=require('playwright'),assert=require('node:assert/strict');
(async()=>{const b=await chromium.launch({headless:true,channel:'chrome'});const p=await b.newPage({viewport:{width:1440,height:1000},reducedMotion:'reduce'});let errors=[];p.on('pageerror',e=>errors.push(e.message));try{await p.goto('http://127.0.0.1:18795');await p.locator('.email-item').first().waitFor();assert.ok(await p.evaluate(()=>_systemConfig.accounts.every(a=>a.user.endsWith('@example.test'))));await p.evaluate(()=>hideAppPreloader());await p.waitForTimeout(500);for(const theme of ['light','dark']){
await p.evaluate(t=>{applyTheme(t);openCompose({subject:'files',body_html:'<p>test</p>',to_addr:'test@example.test'});},theme);await p.waitForTimeout(250);
await p.evaluate(()=>{const dt=new DataTransfer();dt.items.add(new File(['dropped text'],'拖入.txt',{type:'text/plain'}));document.querySelector('.compose-card').dispatchEvent(new DragEvent('drop',{bubbles:true,cancelable:true,dataTransfer:dt}));});await p.waitForFunction(()=>composeAttachments.length===1);
await p.evaluate(()=>{const dt=new DataTransfer();dt.items.add(new File(['pasted text'],'粘贴.txt',{type:'text/plain'}));document.getElementById('compose-message').dispatchEvent(new ClipboardEvent('paste',{bubbles:true,cancelable:true,clipboardData:dt}));});await p.waitForFunction(()=>composeAttachments.length===2);
await p.locator('[data-preview-compose-attachment="0"]').dispatchEvent('click');await p.locator('.file-preview pre').waitFor();assert.equal(await p.locator('.file-preview pre').textContent(),'dropped text');assert.ok((await p.locator('[data-preview-download]').getAttribute('href')).includes('/api/drafts/'));await p.locator('.file-preview button[aria-label="关闭预览"]').dispatchEvent('click');await p.screenshot({path:`build/compose-files-${theme}.png`});
await p.evaluate(()=>{clearTimeout(draftSaveTimer);draftSession.canceled=true;closeCompose();specialMailbox='sent';sentMessages=[{id:901,status:'sent',to_addr:'again@example.test',subject:'Original sent',body_html:'<p>original body</p>',attachments:[{filename:'原附件.txt',size:3,data_base64:'YWJj',content_type:'text/plain'}]}];selectSpecialMessage(901);});await p.locator('#btn-edit-special').dispatchEvent('click');await p.waitForFunction(()=>document.body.classList.contains('compose-open'));assert.equal(await p.locator('#compose-to').inputValue(),'again@example.test');assert.equal(await p.evaluate(()=>currentDraftId),null);assert.equal(await p.evaluate(()=>composeAttachments[0].data_base64),'YWJj');assert.equal(await p.evaluate(()=>sentMessages[0].id),901);await p.evaluate(()=>{clearTimeout(draftSaveTimer);draftSession.canceled=true;closeCompose();});
}
await p.route('**/api/emails/902/attachments/0*',route=>route.fulfill({body:'remote attachment',contentType:'text/plain'}));
await p.evaluate(()=>{specialMailbox='sent';sentMessages=[{id:-902,_remote:true,remote_email_id:902,status:'sent',subject:'Remote',to_addr:'remote@example.test',body_html:'<p>remote body</p>',attachments:[{name:'远程.txt',size:17}]}];selectSpecialMessage(-902);});await p.locator('#btn-edit-special').dispatchEvent('click');await p.waitForFunction(()=>document.body.classList.contains('compose-open'));assert.equal(await p.evaluate(()=>atob(composeAttachments[0].data_base64)),'remote attachment');assert.equal(await p.evaluate(()=>currentDraftId),null);
assert.deepEqual(errors,[]);console.log('PASS both themes: file drop, file paste, draft attachment preview/download link, sent edit as new with original intact');}finally{await b.close();}})().catch(e=>{console.error(e);process.exit(1)});
