const fs = require('node:fs');
const vm = require('node:vm');
const assert = require('node:assert/strict');
const source = fs.readFileSync(require('node:path').join(__dirname, '../app/web/static/app.js'), 'utf8');
const start = source.indexOf('function getRiskLabel(');
const end = source.indexOf('// ===== 数据加载', start);
const context = vm.createContext({});
vm.runInContext(source.slice(start, end), context);
assert.equal(context.getRiskLabel(95, 'clean', {feedback:'fp', reviewed:1}).text, '已确认误报');
assert.equal(context.getRiskLabel(0, 'clean', {feedback:'fn'}).class, 'danger');
assert.equal(context.getRiskLabel(95, 'clean', {feedback:'fp', reviewed:0}).class, 'danger');
assert.equal(context.getRiskLabel(95, 'unreviewed').class, 'muted');
assert.equal(context.getRiskLabel(50, 'suspicious').class, 'warn');
assert.equal(context.getRiskLabel(0, 'clean').class, 'success');
assert.equal(context.needsRiskAttention({score:95, verdict:'phishing', feedback:'fp', reviewed:1}), false);
assert.equal(context.needsRiskAttention({score:0, verdict:'clean', feedback:'fn', reviewed:1}), false);
assert.equal(context.needsRiskAttention({score:0, verdict:'clean', feedback:'fn', reviewed:0}), true);
assert.equal(context.needsRiskAttention({score:90, verdict:'phishing', pending_action:'trash'}), false);
assert.equal(context.needsRiskAttention({score:90, verdict:'phishing', status:'trash'}), false);
assert.ok(context.buildRiskGauge(95, context.getRiskLabel(95, 'clean', {feedback:'fp', reviewed:1})).includes('原始自动评分'));
assert.ok(!context.buildRiskGauge(0, context.getRiskLabel(0, 'unreviewed')).includes('undefined'));
assert.match(source, /class="phishing-alert-banner"/, 'Phishing detail must show a prominent safety alert');
assert.match(source, /risk-attention-intro/, 'Phishing safety result must receive a finite attention animation');
assert.match(source, /risk-alert-dot/, 'Phishing list badge must include an animated alert marker');
console.log('Human feedback precedence, original score labeling and neutral gauge passed');
